# Google Cloud Storage Bucket for raw CSV and API extracts
resource "google_storage_bucket" "raw_data_bucket" {
  name          = var.gcs_bucket_name
  location      = var.gcp_region
  force_destroy = true

  storage_class = "STANDARD"

  uniform_bucket_level_access = true

  # Transition raw files to cheaper Nearline storage after 90 days
  lifecycle_rule {
    condition {
      age = 90
    }
    action {
      type          = "SetStorageClass"
      storage_class = "NEARLINE"
    }
  }
}

# BigQuery Dataset for raw ingestion (e.g. Airbyte destination)
resource "google_bigquery_dataset" "raw_dataset" {
  dataset_id                  = var.bq_raw_dataset_id
  friendly_name               = "NYC Taxi Raw Ingestion"
  description                 = "Target dataset for raw Airbyte CSV ingestion."
  location                    = var.gcp_region
  default_table_expiration_ms = null # Keep raw data permanently
}

# BigQuery Dataset for dbt development models
resource "google_bigquery_dataset" "dbt_dev_dataset" {
  dataset_id    = "dbt_dev_nyc_taxi"
  friendly_name = "NYC Taxi dbt Development"
  description   = "Staging and core development tables generated by dbt."
  location      = var.gcp_region
}

# BigQuery Dataset for analytical marts (Production)
resource "google_bigquery_dataset" "marts_dataset" {
  dataset_id    = var.bq_marts_dataset_id
  friendly_name = "NYC Taxi Analytics Marts"
  description   = "Aggregated, production-ready analytics tables for BI dashboards."
  location      = var.gcp_region
}
